databases:
  - name: tutorplus
    databaseName: tutorplus
    user: tutorplus

services:
  - type: web
    name: tutorplus
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tutorplus
          property: connectionString
      - key: a299b9a249739019c75997e92574758c
        sync: false
